apiVersion: v1
kind: Service
metadata:
  labels:
    app: ducta11-kubernetes-udagram-frontend
  name: ducta11-kubernetes-udagram-frontend-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/ducta11-kubernetes-udagram-frontend-svc
spec:
  ports:
  - port: 8100
    protocol: TCP
    targetPort: 8100
  selector:
    app: ducta11-kubernetes-udagram-frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
